### ISSUE TITLE
uuid_it create two records in uuid table

### ISSUE THREAD

**Issue by t0d0r** [aduffeck/uuid_it#1]
I use rails 3.0.10

when do j = Job.new and then j.uuid in uuids table I got two records with different uuid's

```
select * from uuids;
    14|c06038d2-ceb9-11e0-3e9f-53b6c1cacaf9|7|Job
    15|d63faf84-ceb9-11e0-409f-53b6c1cacaf9|8|Job
    16|f4a47fcc-ceb9-11e0-429f-53b6c1cacaf9|9|Job
    17|f4a3f19c-ceb9-11e0-419f-53b6c1cacaf9|9|Job
```

Job with id 8 have only one line, because I execute j.save before j.uuid

**Comment by aduffeck** [comment]
Hey, thanks for the report.
I pushed the gem 0.1.2 to rubygems.org which includes the fix for this issue.
