### ISSUE TITLE
Can't mass-assign protected attributes: uuid

### ISSUE THREAD

**Issue by amitpatelx** [aduffeck/uuid_it#7]
I followed all [installation and usage steps](https://github.com/aduffeck/uuid_it#readme).  I am getting this error while trying to create model which is tagged as `uuid_it`

**Environment:**
- rails 3.2.5 
- ruby 1.9.3p194
- uuid_it (0.1.4)

Is that anything missing here?

**Comment by aduffeck** [comment]
This has been fixed in ac099b7c5daca31aafcdf49be1f43d18233051b2
